on:
  push:
    paths:
      - '.github/workflows/push_to_pages.yml'
      - 'export/**'
  pull_request:
    paths:
      - '.github/workflows/push_to_pages.yml'
      - 'export/**'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:

    - uses: actions/checkout@v2

    - name: Build and Export
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
        - run: npm install
        - run: npm run export
          env:
            CI: true

    - name: Deploy to gh-pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: __sapper__/export
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
