name: Deploy to GitHub Pages
on:
  push:	
    branches:	
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build and Export
      run: |
        npm install
        npm run export
      env:
        CI: true
    
    - name: Add CNAME
      run: echo "blog.shiryel.com" > CNAME

    - name: Deploy to gh-pages
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: __sapper__/export
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
